---
# f5-loadbalancer roles main.yml

- include_tasks: facts.yml 
  tags: [facts]

- include_tasks: license.yml
  tags: [license]

- include_tasks: postprovision.yml
  tags: [postprovision, prepare]

- include_tasks: balance.yml 
  tags: [balance]

- include_tasks: poolmember.yml
  tags: [poolmember]

- include_tasks: pool_report.yml
  tags: [report]

- include_tasks: 
    file: reverseengineer.yml
    apply: 
      tags: always
  tags: [reverse]
