---
# learn from F5 and push back to selectable destinations

- name: grep data from F5 device
  f5networks.f5_modules.bigip_device_info:
    provider: "{{ f5_provider }}"
    gather_subset:
      - ltm-pools
  register: _device_info

- debug: 
    var: _device_info.ansible_facts.ansible_net_ltm_pools
    verbosity: 2

- name: Ansible Tower push back block
  block:
  - name: make sure about inventory itself on Tower
    awx.awx.tower_inventory:
      tower_host: "{{ f5_tower_host }}"
      tower_username: "{{ f5_tower_username }}"
      tower_password: "{{ f5_tower_password }}"
      validate_certs: no
      name: "{{ f5_reverse_tower_inventory }}"
      description: managed by Ansible F5 role only

  - name: push back to Ansible Tower
    include_tasks:
      file: reverseengineer_inner.yml
    loop: "{{ _device_info.ansible_facts.ansible_net_ltm_pools }}"
    loop_control:
      loop_var: pool
      label: "{{ pool.name }}"
  when: f5_reverse_dest == 'tower'
